mutation CreateShareholder($input: CreateShareholderInput!) {
  createShareholder(input: $input) {
    id
    name
  }
}

mutation UpdateShareholder($input: UpdateShareholderInput!) {
  updateShareholder(input: $input) {
    id
    name
  }
}

mutation DeleteShareholder($input: DeleteShareholderInput!) {
  deleteShareholder(input: $input) {
    id
  }
}

mutation UpdateCompany($input: UpdateCompanyInput!) {
  updateCompany(input: $input) {
    id
    name
    unallocatedOptions
  }
}

mutation CreateFinancialInstrument($input: CreateFinancialInstrumentInput!) {
  createFinancialInstrument(input: $input) {
    id
    name
  }
}

mutation UpdateFinancialInstrument($input: UpdateFinancialInstrumentInput!) {
  updateFinancialInstrument(input: $input) {
    id
    name
  }
}

mutation DeleteFinancialInstrument($input: DeleteFinancialInstrumentInput!) {
  deleteFinancialInstrument(input: $input) {
    id
  }
}

mutation UpdateNextRound($input: UpdateNextRoundInput!) {
  updateNextRound(input: $input) {
    companyId
  }
}

mutation CreateInvestor($input: CreateInvestorInput!) {
  createInvestor(input: $input) {
    id
    name
    amount
  }
}

mutation UpdateInvestor($input: UpdateInvestorInput!) {
  updateInvestor(input: $input) {
    id
    name
    amount
  }
}

mutation DeleteInvestor($input: DeleteInvestorInput!) {
  deleteInvestor(input: $input) {
    id
  }
}

mutation Auth($input: AuthInput!) {
  auth(input: $input) {
    company {
      id
      name
      unallocatedOptions
      fullyDilutedShares
      outstandingOptions
      shareholderFullyDiluted
      fullyDilutedSubtotalPercentage
      fullyDilutedTotal
      users {
        id
        email
        company {
          id
        }
        createdAt
        updatedAt
      }
      financialInstruments {
        id
        name
        instrumentType
        principal
        interestRate
        valuationCap
        discountRate
        conversionDate
        issueDate
        principalAndInterest
        accruedInterest
      }
      nextRound {
        companyId
        preMoneyValuation
        roundSize
        buyingPower
        implicitValuation
        investors {
          id
          name
          amount
        }
      }
      conversionResults {
        conversionPrice
        discountedSharePrice
        holderId
        holderName
        instrumentType
        sharesConverted
        valuationCapDenominator
        valuationCapSharePrice
      }
      shareholders {
        id
        name
        dilutedShares
        outstandingOptions
        createdAt
        updatedAt
        companyId
      }
      capTable {
        sharesExcludingOptions
        sharesExcludingOptionsPercentage
        shareholders {
          name
          fullyDilutedTotal
          fullyDilutedPercentage
        }
        unallocatedOptions
        unallocatedOptionsPercentage
        totalShares
        totalSharesPercentage
      }
      createdAt
      updatedAt
    }
    errors
  }
}
